// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbRMzDaImFghT7u1ihqz6WUNSi7eUQ6k',
    appId: '1:271937986326:web:992ae31583222fc7c8ba37',
    messagingSenderId: '271937986326',
    projectId: 'real-link-e23de',
    authDomain: 'real-link-e23de.firebaseapp.com',
    storageBucket: 'real-link-e23de.appspot.com',
    measurementId: 'G-H2W1DJMNS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmrrVYO58UNM2UJCkMQgWxLy0Etv_3zw',
    appId: '1:271937986326:android:6be0338d310abc4fc8ba37',
    messagingSenderId: '271937986326',
    projectId: 'real-link-e23de',
    storageBucket: 'real-link-e23de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-YJzBwonbEuWmauv3MIlZh_9xHbSsAs',
    appId: '1:271937986326:ios:3744f2d9aa174180c8ba37',
    messagingSenderId: '271937986326',
    projectId: 'real-link-e23de',
    storageBucket: 'real-link-e23de.appspot.com',
    iosClientId: '271937986326-rn8acij956ee6d4hqinm01v7kfbg6ll5.apps.googleusercontent.com',
    iosBundleId: 'com.example.realLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-YJzBwonbEuWmauv3MIlZh_9xHbSsAs',
    appId: '1:271937986326:ios:3744f2d9aa174180c8ba37',
    messagingSenderId: '271937986326',
    projectId: 'real-link-e23de',
    storageBucket: 'real-link-e23de.appspot.com',
    iosClientId: '271937986326-rn8acij956ee6d4hqinm01v7kfbg6ll5.apps.googleusercontent.com',
    iosBundleId: 'com.example.realLink',
  );
}
