// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdOn-bFAaegqhcjkgzaBipmJDHjKjJxA',
    appId: '1:1094588054418:web:10c745509dd01c3ed5df4b',
    messagingSenderId: '1094588054418',
    projectId: 'real-link-64ae6',
    authDomain: 'real-link-64ae6.firebaseapp.com',
    storageBucket: 'real-link-64ae6.appspot.com',
    measurementId: 'G-PRJQ7M5FEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCueh3xKlRUqxqO_4G9FsL4uTmdDZesXRM',
    appId: '1:1094588054418:android:3dab6671905006dfd5df4b',
    messagingSenderId: '1094588054418',
    projectId: 'real-link-64ae6',
    storageBucket: 'real-link-64ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbxrrkNuNPh0ea8RyRbl9igJao7-NCkA',
    appId: '1:1094588054418:ios:a5373d331b1620f4d5df4b',
    messagingSenderId: '1094588054418',
    projectId: 'real-link-64ae6',
    storageBucket: 'real-link-64ae6.appspot.com',
    iosClientId: '1094588054418-vct447v0nhors8ji5mt0068jf7lbgohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.realLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUbxrrkNuNPh0ea8RyRbl9igJao7-NCkA',
    appId: '1:1094588054418:ios:a5373d331b1620f4d5df4b',
    messagingSenderId: '1094588054418',
    projectId: 'real-link-64ae6',
    storageBucket: 'real-link-64ae6.appspot.com',
    iosClientId: '1094588054418-vct447v0nhors8ji5mt0068jf7lbgohe.apps.googleusercontent.com',
    iosBundleId: 'com.example.realLink',
  );
}
